# Site settings
title: Wollongong IT Society (WITS)
email: contact@uowits.com
description: >
  WITS is a student club at the University of Wollongong.
baseurl: "/"
url: "/"
domain: "http://uowits.com"
twitter_username: uowits
github_username:  uwits

# Build settings
markdown: kramdown

collections:
 events:
  output: true
  permalink: /events/:path/
