# Site settings
title: Wollongong IT Society (WITS)
email: contact@uowits.com
description: WITS is a student club at the University of Wollongong.
baseurl: "/"
url: "/"
domain: "http://www.uowits.com"
twitter_username: uowits
github_username:  uwits
membercount: 602

# Build settings
markdown: kramdown
future: true

collections:
 events:
  output: true
  permalink: /events/:path/
 exec:
  output: true
  permalink: /exec/:path/
